---
title: "PC4: Linear Regression"
author: 
  - "Jack Colt"
  - "Finn Balfe"
  - "John Brune"
  - "Alex Musco"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r setup}
library(tidyverse)
library(janitor)
library(gganimate)
library(av)
corruption <- read.csv("corruption_perception_index.csv")
happiness <- read.csv("hapiscore.csv")
```

```{r}
corruption <- corruption |>
  clean_names() |>
  pivot_longer(cols = c(x2012, x2013, x2014, x2015, x2016, x2017), 
               names_to = "year",
               values_to = "corruption") |>
  filter(!(is.na(corruption)))

happiness <- happiness |>
  clean_names() |>
  select(country, x2012, x2013, x2014, x2015, x2016, x2017) |>
  pivot_longer(cols = c(x2012, x2013, x2014, x2015, x2016, x2017), 
               names_to = "year",
               values_to = "happiness") |>
  filter(!(is.na(happiness)))

data <- happiness |>
  inner_join(corruption, join_by(country, year)) |>
  mutate(country = fct(country),
         year = as.numeric(substr(year, 2, 5)))
```

##Data Visualization

```{r}
#Plot 1
##The relationship between the two quantitative variables you are investigating.
data |> 
  ggplot(aes(x = corruption, y = happiness)) +
  geom_point() +
  labs(title = "Title",
       x = "Corruption Perception Index",
       y = "World Happiness Report")
```

*Discuss plot 1*

```{r}
#Plot 2
##How this relationship (from #1) has changed over time.
anim <- data |> 
  ggplot(aes(x = corruption, y = happiness)) +
  geom_point() +
  labs(title = "Year: {frame_time}", 
       x = "Corruption Perception Index",
       y = "World Happiness Report") +
  transition_time(year) +
  ease_aes('linear')

animate(anim + enter_fade() + exit_fly(y_loc = 1),
        renderer = av_renderer())
```

*Discuss plot 2*

##Linear Regression

```{r}
data_by_country <- data |>
  group_by(country) |>
  summarise(happiness = mean(happiness),
            corruption = mean(corruption))

data_lm <- lm(happiness ~ corruption, data = data_by_country)
summary(data_lm)
```
$$ŷ=36.03181+0.40679x$$
*Interpret coefficients here*

##Model Fit

```{r}
#Create table
```

